version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    ports:
      - 4000:4000
# A network which allows container to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
